// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:android:deb017622c8c4d0cb91cdd',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    storageBucket: 'request-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:ios:abc123def456ghi789',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    storageBucket: 'request-marketplace.firebasestorage.app',
    iosBundleId: 'lk.alphabet.requestmarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:ios:abc123def456ghi789',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    storageBucket: 'request-marketplace.firebasestorage.app',
    iosBundleId: 'lk.alphabet.requestmarketplace',
  );
}
