#!/bin/bash

echo "🔥 Firebase Storage Setup Guide 🔥"
echo "=================================="
echo ""
echo "1. Open Firebase Console:"
echo "   https://console.firebase.google.com/project/request-marketplace"
echo ""
echo "2. Go to Storage section"
echo ""
echo "3. Click 'Get Started'"
echo ""
echo "4. Choose 'Start in test mode' (we have custom rules ready)"
echo ""
echo "5. Select location: asia-south1 (Mumbai) or asia-southeast1 (Singapore)"
echo ""
echo "6. Click 'Done'"
echo ""
echo "7. After setup, run:"
echo "   firebase deploy --only storage"
echo ""
echo "8. Then test image upload in the app!"
echo ""
echo "If you get billing errors, you may need to enable billing for the project."
echo "Storage has a generous free tier that should be more than enough for testing."
