// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:web:placeholder',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    authDomain: 'request-marketplace.firebaseapp.com',
    storageBucket: 'request-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:android:27570ce58b7a8346b91cdd',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    storageBucket: 'request-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:ios:placeholder',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    storageBucket: 'request-marketplace.firebasestorage.app',
    iosBundleId: 'lk.alphabet.request',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:macos:placeholder',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    storageBucket: 'request-marketplace.firebasestorage.app',
    iosBundleId: 'lk.mac.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtuD42SzwxKmSY5p-x5olFex2U_S9YrMk',
    appId: '1:355474518888:windows:placeholder',
    messagingSenderId: '355474518888',
    projectId: 'request-marketplace',
    storageBucket: 'request-marketplace.firebasestorage.app',
  );
}
