// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5hb6Ydkp__EZgX-kRjJgtOKZKg8TNkJg',
    appId: '1:635550436472:web:72ee20ad95cdcf65c1c86a',
    messagingSenderId: '635550436472',
    projectId: 'request-marketplace-45a59',
    authDomain: 'request-marketplace-45a59.firebaseapp.com',
    storageBucket: 'request-marketplace-45a59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hb6Ydkp__EZgX-kRjJgtOKZKg8TNkJg',
    appId: '1:635550436472:android:placeholder',
    messagingSenderId: '635550436472',
    projectId: 'request-marketplace-45a59',
    storageBucket: 'request-marketplace-45a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5hb6Ydkp__EZgX-kRjJgtOKZKg8TNkJg',
    appId: '1:635550436472:ios:placeholder',
    messagingSenderId: '635550436472',
    projectId: 'request-marketplace-45a59',
    storageBucket: 'request-marketplace-45a59.firebasestorage.app',
    iosBundleId: 'lk.alphabet.request',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5hb6Ydkp__EZgX-kRjJgtOKZKg8TNkJg',
    appId: '1:635550436472:macos:placeholder',
    messagingSenderId: '635550436472',
    projectId: 'request-marketplace-45a59',
    storageBucket: 'request-marketplace-45a59.firebasestorage.app',
    iosBundleId: 'lk.mac.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5hb6Ydkp__EZgX-kRjJgtOKZKg8TNkJg',
    appId: '1:635550436472:windows:placeholder',
    messagingSenderId: '635550436472',
    projectId: 'request-marketplace-45a59',
    storageBucket: 'request-marketplace-45a59.firebasestorage.app',
  );
}
