name: Backend Deploy (Staging)

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy-staging.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Image (Staging)
    runs-on: ubuntu-latest
    concurrency:
      group: backend-build-staging-${{ github.ref }}
      cancel-in-progress: false
    env:
      GHCR_USER: ${{ secrets.GHCR_USER }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare lowercase owner
        id: vars
        run: echo "owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      - name: Log in to GHCR
        if: ${{ env.GHCR_USER != '' && env.GHCR_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USER }}
          password: ${{ env.GHCR_TOKEN }}
      - name: Log in to GHCR (fallback to GITHUB_TOKEN)
        if: ${{ env.GHCR_USER == '' || env.GHCR_TOKEN == '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lower }}/request-backend:staging
            ghcr.io/${{ steps.vars.outputs.owner_lower }}/request-backend:${{ github.sha }}-stg

  deploy:
    name: Deploy to Staging Server (SSH)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ secrets.STAGING_DEPLOY_HOST != '' && secrets.STAGING_DEPLOY_USER != '' && secrets.STAGING_DEPLOY_SSH_KEY != '' }}
    environment: staging
    concurrency:
      group: backend-deploy-staging
      cancel-in-progress: true
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          GHCR_USER: ${{ secrets.GHCR_USER }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          host: ${{ secrets.STAGING_DEPLOY_HOST }}
          username: ${{ secrets.STAGING_DEPLOY_USER }}
          key: ${{ secrets.STAGING_DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            REPO_OWNER="${{ github.repository_owner }}"
            IMAGE_OWNER="$(echo "$REPO_OWNER" | tr '[:upper:]' '[:lower:]')"
            IMAGE_BASE="ghcr.io/${IMAGE_OWNER}/request-backend"
            IMAGE="$IMAGE_BASE:${{ github.sha }}-stg"
            echo "[Deploy] Login if needed"
            if [ -n "$GHCR_TOKEN" ] && [ -n "$GHCR_USER" ]; then
              echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            fi
            docker pull "$IMAGE"
            sudo mkdir -p /opt/request-backend
            sudo chown $USER:$USER /opt/request-backend
            if [ "$(docker ps -aq -f name=request-backend-stg)" ]; then
              docker rm -f request-backend-stg || true
            fi
            docker run -d \
              --name request-backend-stg \
              --restart unless-stopped \
              --env-file /opt/request-backend/production.env \
              -p 127.0.0.1:3101:3001 \
              "$IMAGE"
            for i in $(seq 1 30); do
              if curl -fsS http://127.0.0.1:3101/health >/dev/null 2>&1; then
                echo "[Deploy] Staging healthy"
                break
              fi
              echo "[Deploy] Waiting... ($i/30)"
              sleep 2
            done
            curl -fsS http://127.0.0.1:3101/health >/dev/null